---
apiVersion: v1
kind: Secret
metadata:
  name: openai-token
  namespace: ai-lab-1
type: Opaque
stringData:
  Authorization: "$OPENAI_API_KEY"
---
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gpt-config
  namespace: ai-lab-1
spec:
  provider: OpenAI
  model: "gpt-4.1-nano"
  apiKeySecret: "openai-token"
  apiKeySecretKey: "Authorization"
  openAI:
    baseUrl: "http://agentgateway-proxy.agentgateway-system.svc.cluster.local:8082/v1"

---
apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: helper-agent
  namespace: ai-lab-1
spec:
  type: Declarative
  declarative:
    modelConfig: gpt-config
    systemMessage: "You are a helpful assistant running on k3s."
